#server:
#  port: 9090

spring:
  profiles:
    active: dev
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 131421
    timeout: 5000
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 131421
    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      filters: stat,wall,slf4j,config
#      max-active: 100
#      initial-size: 1
#      max-wait: 60000
#      min-idle: 1
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: select 'x'
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-open-prepared-statements: 50
#      max-pool-prepared-statement-per-connection-size: 20


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wlxy.example1.model
app:
  info: This is test
  author: wu
  email: 1124409490@qq.com
  swaggerTitle: 这是我的第一个swagger在线文档
  swaggerContactName: 吴少全
  swaggerContactWebUrl: http://www.baidu.com
  swaggerContactEmail: 1124409490@qq.com
  swaggerVersion: v1.0.0
  swaggerDescription: springboot 在线接口文档
  swaggerTermsOfServiceUrl: http://www.baidu.com


logging:
  level:
    com.wlxy.example1.dao: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: =countSqlcount